\input texinfo
@c -*-texinfo-*-

@c %**start of header
@setfilename guile-git.info
@documentencoding UTF-8
@include version.texi
@settitle guile-git @value{VERSION}
@c %**end of header


@copying
This manual is for guile-git, version @value{VERSION}.

Copyright @copyright{} 2017 Erik Edrosa
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end copying

@titlepage
@title guile-git Reference Manual

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents


@ifnottex
@node Top
@top guile-git

This manual is for guile-git, version @value{VERSION}.
@end ifnottex

@menu
* Introduction::     About guile-git.
* Installation::     Installing guile-git.

Tutorial sections
* Concepts::         Basic concepts for understanding git.
* Examples::         Simple examples for using guile-git.

Reference sections
* Bindings::         libgit2 setup.
* Repository::       Creating and accessing git repositories.
* Objects::          Git blobs, trees, commits, and tags.
* References::       Git references.
* Procedure Index::
@end menu

@node Introduction
@chapter Introduction

Guile-git is a GNU Guile library providing bindings to libgit2.

@node Installation
@chapter Installation

@menu
* Requirements::      Software needed to build and run guile-git.
* Building::
@end menu

@node Requirements
@section Requirements

Guile-git depends on the following packages:

@itemize
@item
@url{https://www.gnu.org/software/guile/, GNU Guile}
@item
@url{https://libgit2.github.com/, libgit2}
@item
@url{https://github.com/TaylanUB/scheme-bytestructures, guile-bytestructures}
@end itemize

@node Building
@section Building

@node Concepts
@chapter Concepts

@node Examples
@chapter Examples

@node Bindings
@chapter Bindings

@node Repository
@chapter Repository

@menu
* Repository: git-repository.   Creating and opening repositories.
* Clone: git-clone.             Cloning git repositories.
* Status: git-status.           Git status.
* Checkout: git-checkout.       Git checkout.
@end menu

@node git-repository
@section Repository

@node git-clone
@section Clone

@node git-status
@section Status

@node git-checkout
@section Checkout

@node Objects
@chapter Objects

@menu
* OID: git-oid.                Git Object IDs.
* Object: git-object.          Git objects.
* Blob: git-blob.              Git blobs.
* Tree: git-tree.              Git trees.
* Commit: git-commit.          Git commits.
* Tag: git-tag.                Git tags.
@end menu

@node git-oid
@section OID

@node git-object
@section Object

@node git-blob
@section Blob

@node git-tree
@section Tree

@node git-commit
@section Commit

@node git-tag
@section Tag

@node References
@chapter References

@menu
* Reference: git-reference.   Git references.
* Branch: git-branch.         Git branches.
* Remote: git-remote.         Git remotes.
@end menu

@node git-reference
@section Reference

@node git-branch
@section Branch

@node git-remote
@section Remote

@node Procedure Index
@unnumbered Procedure Index

@printindex fn 

@bye
