\input texinfo
@c -*-texinfo-*-

@c %**start of header
@setfilename guile-git.info
@documentencoding UTF-8
@include version.texi
@settitle guile-git @value{VERSION}
@c %**end of header


@copying
This manual is for guile-git, version @value{VERSION}.

Copyright @copyright{} 2017 Erik Edrosa
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end copying

@titlepage
@title guile-git Reference Manual

@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents


@ifnottex
@node Top
@top guile-git

This manual is for guile-git, version @value{VERSION}.
@end ifnottex

@menu
* Introduction::     About guile-git.
* Installation::     Installing guile-git.

Tutorial sections
* Concepts::         Basic concepts for understanding git.
* Examples::         Simple examples for using guile-git.

Reference sections
* Bindings::         libgit2 setup.
* Repository::       Creating and accessing git repositories.
* Objects::          Git blobs, trees, commits, and tags.
* References::       Git references.
* Procedure Index::
@end menu

@node Introduction
@chapter Introduction

Guile-git is a GNU Guile library providing bindings to libgit2.

@node Installation
@chapter Installation

@menu
* Requirements::      Software needed to build and run guile-git.
* Building::
@end menu

@node Requirements
@section Requirements

Guile-git depends on the following packages:

@itemize
@item
@url{https://www.gnu.org/software/guile/, GNU Guile}
@item
@url{https://libgit2.github.com/, libgit2}
@item
@url{https://github.com/TaylanUB/scheme-bytestructures, guile-bytestructures}
@end itemize

@node Building
@section Building

@node Concepts
@chapter Concepts

@node Examples
@chapter Examples

@node Bindings
@chapter Bindings

The module @code{git bindings} provide several definitions for
interacting with libgit2.  The main procedure is @code{libgit2-init!}
which must be called before any other guile-git procedure is called.

@deffn {Scheme Procedure} libgit2-init!
Return the number of initializations of libgit2 or an error code.

Initializes the global state of libgit2.  The procedure must be called
before any other procedure is called and may be called multiple times. 
@end deffn

@deffn {Scheme Procedure} libgit2-shutdown!
Return the number of remaining initializations of libgit2 or an error
code.

The procedure cleans up the global state of libgit2 created by
@code{libgit2-init!}.
@end deffn

@node Repository
@chapter Repository

@menu
* Repository: git repository.   Creating and opening repositories.
* Clone: git-clone.             Cloning git repositories.
* Status: git-status.           Git status.
* Checkout: git-checkout.       Git checkout.
@end menu

@node git repository
@section Repository

@deffn {Scheme Procedure} repository-init directory [is-bare]
Return a repository created at @var{directory} or throws an error if
there was an issue creating the repository.  When @var{is-bare} is
true, it creates a bare repository at @var{directory}.  When
@var{is-bare} is false, a .git directory is created at @var{directory}.
@end deffn

@deffn {Scheme Procedure} repository-open directory
Return a repository found at @var{directory} or throws an error if no
repository is found.  @var{directory} must be a git repository folder
or a working directory with a .git directory.  The procedure will open
both normal and bare repositories.
@end deffn

@deffn {Scheme Procedure} repository-open-ext directory flags [ceiling-path]
Return a repository by searching @var{directory} or parent directories
depending on @var{flags}.  @var{flags} is a list of symbols which
control the behavior of the procedure and include the following
symbols.
@table @code
@item no-search
Do not search parent directories.

@item cross-fs
Search across filesystem boundaries.

@item bare
Open repository as a bare repo.

@item no-.git
Do not check by appending .git to directory.

@item from-env
Use git environment variables.
@end table
@var{ceiling-path} is an optional list of directories where the search
for the repository should terminate.
@end deffn

@deffn {Scheme Procedure} repository-discover start-directory [across-fs] [ceiling-path]

@end deffn

@node git-clone
@section Clone

@node git-status
@section Status

@node git-checkout
@section Checkout

@node Objects
@chapter Objects

@menu
* OID: git-oid.                Git Object IDs.
* Object: git-object.          Git objects.
* Blob: git-blob.              Git blobs.
* Tree: git-tree.              Git trees.
* Commit: git-commit.          Git commits.
* Tag: git-tag.                Git tags.
@end menu

@node git-oid
@section OID

@node git-object
@section Object

@node git-blob
@section Blob

@node git-tree
@section Tree

@node git-commit
@section Commit

@node git-tag
@section Tag

@node References
@chapter References

@menu
* Reference: git-reference.   Git references.
* Branch: git-branch.         Git branches.
* Remote: git-remote.         Git remotes.
@end menu

@node git-reference
@section Reference

@node git-branch
@section Branch

@node git-remote
@section Remote

@node Procedure Index
@unnumbered Procedure Index

@printindex fn 

@bye
